# 1. A simple MATLAB function

In [3]:
import numpy as np

# identity matrix
A = np.eye(5, dtype=int)

print(A)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


# 2. Linear regression with one variable
## 2.1 Plotting the data